### PR TITLE
Lowered the iOS deployment target from 12.1 to 9.0

### LINKED ISSUE #17: clang: error: no such file or directory libRNCPushNotificationIOS.a
# Bug
When you try to make a build or archive in Xcode 10.2

## Environment info

RN : 0.59.10
Xcode: 10.2.1
React native info output:

```
clang: error: no such file or directory: '/Users/xxx/Library/Developer/Xcode/DerivedData/xxx-ewerqswkditpomciyhywhltemfhd/Build/Products/Release-iphoneos/libRNCPushNotificationIOS.a'
Command Ld failed with a nonzero exit code
```

Library version: Latest

## Steps To Reproduce

1. Add libRNCNotificationPush.a to Link Binary
2. Build the project
...

Describe what you expected to happen:

1.Succes

### PR DESCRIPTION
**Pull request by sennevc**
The iOS deployment target was set to 12.1. Since this is higher than the react native default (9.0), the package was left out of release builds and, as a result, making them fail.

Fixes #17

### CODE REVIEW

**Comment by bliang** [comment]
Thanks for making this PR!

**Comment by Natkarock** [comment]
> Thanks for making this PR!

Waiting for this PR!:)

**Comment by alexYopeso** [comment]
when will this be merged?

**Comment by calintamas** [comment]
+1

**Comment by biaji** [comment]
What happened to this project?  This issue has consum lots of time of many developers..  And after all these days.  It still there?

**Comment by orta** [comment]
Let's get this in

**Comment by naveendevs** [comment]
> Let's get this in

Thanks a lot, orta

**Comment by calintamas** [comment]
@orta can you please also publish a patch version w/ this?

**Comment by grit96** [comment]
Any idea when this will be published in a release?

**Comment by orta** [comment]
I don't have NPM access, I'd check out who does and ask them 👍

**Comment by grit96** [comment]
@rafaellincoln @thymikee

**Comment by thymikee** [comment]
Published in v1.0.3

**Comment by gbmahili** [comment]
The left out file **libRNCPushNotificationIOS.a** is stil empty.

**Pull request merged**
