### PR TITLE
Migrate the PushNotificationIOS module from React Native core to the community repo

### PR DESCRIPTION
**Pull request by rafaellincoln**
[Lean Core](https://github.com/facebook/react-native/issues/23313)

- Renamed the native module to `RNCNetInfo` which follows the WebView community library pattern.
- Added an `example` project (Based on RNTester) which does not require a nested `package.json`.
- I have not made any modifications to the native or Javascript code aside from changing the names of variables to reference the new module name.

Example app screenshots:
unadjustednonraw_thumb_b55
unadjustednonraw_thumb_b57
unadjustednonraw_thumb_b56
unadjustednonraw_thumb_b58

### CODE REVIEW

**Comment by rafaellincoln** [comment]
cc @cpojer

**Comment by cpojer** [comment]
This is awesome! I'm gonna give you admin access to this repo and would like to give you push access for npm – what's your npm username?

**Comment by rafaellincoln** [comment]
My npm username is rafaellpa.

**Comment by cpojer** [comment]
I added you to this repo and npm. Please merge whenever you are ready, and publish a release as 1.0.0 on npm, then we can merge the deprecation warning in RN that you already sent out.

It would also be awesome if you could set up CI for this repo!

**Comment by rafaellincoln** [comment]
Thank you @cpojer.
I will merge this PR. I'm going too set up CI and publish a release on npm.

**Pull request merged**
