### PR TITLE
Rename RNPushNotificationIOS.podspec to RNCPushNotificationIOS.podspec

### LINKED ISSUE #11: The name of the given podspec `RNCPushNotificationIOS` doesn't match the expected one `RNPushNotificationIOS`
Should the `RNPushNotificationIOS.podspec` be renamed to `RNCPushNotificationIOS.podspec`?

### PR DESCRIPTION
**Pull request by Gp2mv3**
Avoid autolinking error with RN 60.

Fixes #11

# Summary

I had the error when linking the package in our project. 

## Test Plan

Compiles and executes fine.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅      |
| Android |    ✅      |

## Checklist

- [X] I have tested this on a device

### CODE REVIEW

**Comment by seeya** [comment]
Please merge this!

**Comment by thymikee** [comment]
Thank you @Gp2mv3

**Comment by GertjanReynaert** [comment]
@thymikee Thx for merging! Would you know when this fix would be available on NPM?

**Comment by thymikee** [comment]
I don't have publish access, but working on it

**Comment by GertjanReynaert** [comment]
Thx for the efforts!!!

**Comment by thymikee** [comment]
Published v1.0.2, let me know if it works

**Comment by GertjanReynaert** [comment]
I'll test it functionally in a bit, but I just tried installing that version:
- with `npm install` it succeeds
- wity `yarn add` it fails with this error

> error https://github.com/react-native-community/react-native-push-notification-ios: Extracting tar content of undefined failed, the file appears to be corrupt: "Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?"


Maybe this issue can be of any help? https://github.com/yarnpkg/yarn/issues/3141

**Comment by thymikee** [comment]
@GertjanReynaert use the package from npm:
```
yarn add @react-native-community/push-notification-ios
```

**Comment by GertjanReynaert** [comment]
@thymikee That's what I did:

```
❯ yarn add @react-native-community/push-notification-ios
yarn add v1.17.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error https://github.com/react-native-community/react-native-push-notification-ios: Extracting tar content of undefined failed, the file appears to be corrupt: "Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?"
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by thymikee** [comment]
Yarn shouldn't fetch from GitHub by default, unless you tell it so. Can you remove the entry from `yarn.lock` and `package.json` and try again?

**Comment by GertjanReynaert** [comment]
Installing succeeded, indeed a problem on my side (removed the entry, removed yarn.lock, removed node_modules and yarn cache clean)

I'll give it a try in a few minutes, I'll let you know if I have any issues.

**Comment by GertjanReynaert** [comment]
My build succeeds, runs on my device, I'm able to trigger the permission modal and I receive a device token. I'd say it works, I'll test some more, but I think this build is good 👍 

Thx for your efforts @thymikee !

**Pull request merged**
